# permissions for end users to edit imageversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: update-operator
    app.kubernetes.io/managed-by: kustomize
  name: imageversion-editor-role
rules:
- apiGroups:
  - update.wellcom.rocks
  resources:
  - imageversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.wellcom.rocks
  resources:
  - imageversions/status
  verbs:
  - get
